-- MySQL Script generated by MySQL Workbench
-- mar 17 sep 2019 10:39:21 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `world` ;

-- -----------------------------------------------------
-- Table `world`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`Country` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(3) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Continent` VARCHAR(50) NOT NULL,
  `Region` VARCHAR(100) NULL,
  `SurfaceArea` INT(10) NULL,
  `IndepYear` INT(4) NULL,
  `Population` INT(10) NULL,
  `LifeExpectancy` FLOAT NULL,
  `GNP` INT(10) NOT NULL,
  `GNPold` INT(10) NULL,
  `LocalName` VARCHAR(100) NULL,
  `GovernmentForm` VARCHAR(50) NULL,
  `HaedOfState` VARCHAR(50) NULL,
  `Capital` VARCHAR(50) NULL,
  `Code2` VARCHAR(2) NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `Code`),
  UNIQUE INDEX `Code_UNIQUE` USING BTREE (`Code`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `world`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`City` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `CountryCode` VARCHAR(3) NOT NULL,
  `District` VARCHAR(100) NOT NULL,
  `Population` INT(10) NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_City_CountryCode_idx` (`CountryCode` ASC) VISIBLE,
  CONSTRAINT `fk_City_CountryCode`
    FOREIGN KEY (`CountryCode`)
    REFERENCES `world`.`Country` (`Code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `world`.`CountryLanguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`CountryLanguage` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `CountryCode` VARCHAR(3) NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  `IsOfficial` TINYINT NOT NULL,
  `Percentage` TINYINT(2) NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CountryLanguage_CountryCode_idx` (`CountryCode` ASC) VISIBLE,
  CONSTRAINT `fk_CountryLanguage_CountryCode`
    FOREIGN KEY (`CountryCode`)
    REFERENCES `world`.`Country` (`Code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
